delete_event_example = [
    "Xóa cuộc họp với khách hàng lúc 14:00 ngày mai.",
    "Hủy buổi tập gym lúc 18:00 hôm nay.",
    "Xóa lịch khám sức khỏe vào ngày 10/04.",
    "Hủy sự kiện đọc sách vào 20:00 tối nay.",
    "Xóa lịch kiểm tra tiến độ vào thứ Sáu tuần này.",
    "Hủy cuộc họp nội bộ vào thứ Hai tuần tới.",
    "Xóa sự kiện thanh toán hóa đơn vào ngày 5 tháng này.",
    "Hủy lịch làm việc với nhóm lúc 9:00 sáng mai.",
    "Xóa buổi học tiếng Anh vào thứ Tư tuần này.",
    "Hủy lịch dọn dẹp nhà cửa vào Chủ Nhật tuần này.",
    # Xóa các sự kiện lặp lại
    "Xóa tất cả các buổi tập gym diễn ra vào thứ Ba hàng tuần.",
    "Hủy toàn bộ lịch họp nhóm diễn ra vào mỗi thứ Hai.",
    "Xóa tất cả các buổi học tiếng Anh vào thứ Tư hàng tuần.",
    "Hủy toàn bộ sự kiện đọc sách vào 20:00 mỗi ngày.",
    "Xóa tất cả lịch kiểm tra tiến độ diễn ra vào thứ Sáu hàng tuần.",
    "Hủy lịch thanh toán hóa đơn định kỳ vào ngày 5 hàng tháng.",
    "Xóa lịch họp khách hàng diễn ra mỗi tháng một lần.",
    "Hủy tất cả các buổi dọn dẹp nhà cửa vào Chủ Nhật hàng tuần.",
    "Xóa lịch cập nhật báo cáo tài chính diễn ra mỗi quý một lần.",
    "Hủy toàn bộ lịch kiểm tra bảo mật hệ thống mỗi 12 tuần.",
    # Xóa 1 lần trong chuỗi sự kiện lặp lại
    "Hủy buổi tập gym ngày 10/04 nhưng giữ nguyên các buổi khác.",
    "Xóa cuộc họp nhóm vào thứ Hai tới, nhưng giữ nguyên các cuộc họp khác.",
    "Hủy lịch kiểm tra tiến độ vào thứ Sáu tuần này, nhưng vẫn duy trì lịch hằng tuần.",
    "Xóa buổi học tiếng Anh vào thứ Tư này nhưng giữ nguyên các buổi sau.",
    "Hủy lịch họp khách hàng vào tháng này, nhưng giữ nguyên các tháng khác.",
    "Xóa một lần lịch dọn dẹp nhà cửa vào tuần này nhưng giữ nguyên lịch lặp lại.",
    "Hủy buổi báo cáo tiến độ vào tháng này nhưng vẫn duy trì hằng tháng.",
    "Xóa sự kiện backup dữ liệu vào tuần này, nhưng không ảnh hưởng đến các tuần sau.",
    "Hủy một lần cuộc họp nội bộ vào tuần sau nhưng vẫn duy trì lịch họp định kỳ.",
    "Xóa lịch thanh toán hóa đơn tháng này nhưng vẫn giữ nguyên lịch hằng tháng.",
]
